In [5]:
import polars as pl
import os

In [16]:
ruta_data = pl.read_parquet(
    "/Users/nicolaswilches/ds/projects/iberdrola-ev-network/Ruta a la electrificación de la Movilidad/Datos/2015_01.parquet"
)

In [26]:
ruta_data["CATEGORÍA_VEHÍCULO_ELÉCTRICO"].unique()

shape: (5,)
Series: 'CATEGORÍA_VEHÍCULO_ELÉCTRICO' [str]
[
	null
	"HEV"
	"PHEV"
	"BEV"
	"REEV"
]

In [23]:
personas = pl.read_parquet(
    "/Users/nicolaswilches/ds/projects/iberdrola-ev-network/data/Personas_municipios_2022-01-01_2022-01-06_v2.parquet"
)

In [24]:
personas.head()

shape: (5, 6)
┌────────────┬─────────────────────┬──────┬────────┬─────────────────┬─────────┐
│ date       ┆ overnight_stay_area ┆ age  ┆ gender ┆ number_of_trips ┆ people  │
│ ---        ┆ ---                 ┆ ---  ┆ ---    ┆ ---             ┆ ---     │
│ str        ┆ str                 ┆ str  ┆ str    ┆ str             ┆ f64     │
╞════════════╪═════════════════════╪══════╪════════╪═════════════════╪═════════╡
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 0               ┆ 244.54  │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 1               ┆ 34.94   │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 2               ┆ 64.971  │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 2+              ┆ 89.423  │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ female ┆ 0               ┆ 164.802 │
└────────────┴─────────────────────┴──────┴────────┴─────────────────┴─────────┘